# Basic Information 
lang: en
title: Akira Kawabata
tagline: Ph.D. student at SOKENDAI
position: Ph.D. student
affiliation: The Graduate University for Advanced Studies, SOKENDAI
affiliation_link: https://www.soken.ac.jp/en/
email: kwbt0206@gmail.com
url: https://akirakawabata.github.io
logo: /assets/img/avatar.png
author:
  name: Akira Kawabata
social:
  name: Akira Kawabata
  links:
    - https://scholar.google.com/citations?user=rP1K2-UAAAAJ
    - https://github.com/AkiraKawabata
    - https://www.linkedin.com/in/akira-kawabata-4b0bb7203/

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Akira Kawabata, natural language processing, large language models, scalable oversight, synthetic data generation, SOKENDAI
description: Personal academic website of Akira Kawabata, a Ph.D. student at SOKENDAI working on scalable oversight and synthetic data generation.
canonical: https://akirakawabata.github.io/
google_site_verification: G4NvlpwOW6dMkQfcDxTNHcmjxHEKsZZIh--nPJuk8vs

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=rP1K2-UAAAAJ
cv_link: assets/files/cv_asof_20260401.pdf
github_link: https://github.com/AkiraKawabata
linkedin: https://www.linkedin.com/in/akira-kawabata-4b0bb7203/
#twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
  - cv/
  - vendor/
  - _site/
  - assets/files/cv_asof_202603.pdf
